In [1]:
import numpy as np

def bracelets(a, b):
    matrix = np.zeros(100)
    matrix[0] = a
    matrix[1] = b
    i = 2
    while True:
        matrix[i] = (matrix[i-1] + matrix[i-2]) % 10
        if matrix[i-1] == a and matrix[i] == b:
            break
        i += 1
        if i >= len(matrix):
            break
    matrix = matrix[:i]
    return matrix

In [2]:
print(bracelets(1,5))

[1. 5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0. 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1. 6.
 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1. 2. 3. 5. 8.
 3. 1. 4. 5. 9. 4. 3. 7. 0. 7. 7. 4. 1.]


In [3]:
print(bracelets(2,2))

[2. 2. 4. 6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8. 2. 0. 2.]


In [4]:
print(bracelets(1,3))

[1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1.]


In [5]:
print(bracelets(5,5))

[5. 5. 0. 5.]


In [6]:
print(bracelets(4,2))

[4. 2. 6. 8. 4.]


In [7]:
print(bracelets(0,0))

[0. 0.]
